"""Estado default true

Revision ID: 316058dc07f2
Revises: 86861fa02789
Create Date: 2022-09-10 18:52:23.826011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '316058dc07f2'
down_revision = '86861fa02789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###
