"""Estado default true

Revision ID: 3d738f54577d
Revises: 49c6bec6c055
Create Date: 2022-09-10 18:58:00.587166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d738f54577d'
down_revision = '49c6bec6c055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.String(), nullable=True))
    op.drop_column('usuario', 'pais_modif')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais_modif', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###
