"""Estado default true

Revision ID: 49c6bec6c055
Revises: 316058dc07f2
Create Date: 2022-09-10 18:56:33.994928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c6bec6c055'
down_revision = '316058dc07f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais_modif', sa.String(), nullable=True))
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'pais_modif')
    # ### end Alembic commands ###
