"""Estado default true

Revision ID: 86861fa02789
Revises: bfb25ef73968
Create Date: 2022-09-10 18:51:37.683985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86861fa02789'
down_revision = 'bfb25ef73968'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado2', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
