"""Elimianr columna Pais

Revision ID: 8a8f9b9fec2f
Revises: 3d738f54577d
Create Date: 2022-09-10 18:58:28.856238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8f9b9fec2f'
down_revision = '3d738f54577d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
