"""Estado default true

Revision ID: bfb25ef73968
Revises: ac84a7cb207c
Create Date: 2022-09-10 18:49:17.143024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfb25ef73968'
down_revision = 'ac84a7cb207c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
